/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PokerHandsRange {
  constructor(options: PokerHandsRangeOptions)
  getConcreteLineId(request: ConcreteLineIdRequest): number
  handsByActions(request: HandsByActionsRequest): HandsByActionsResponse
  queryHandStrategy(request: QueryHandStrategyRequest): QueryHandStrategyResponse
  prewarm(request: DimensionInput): PrewarmResponse
  stats(): StatsResponse
}

export interface ActionResult {
  actionName: string
  actionSize: number
  amountBb: number
  frequency: number
  handEv?: number
}

export interface ConcreteLineIdRequest {
  strategy?: string
  playerCount: number
  depthBb: number
  concreteLine: string
}

export interface DimensionInput {
  strategy?: string
  playerCount: number
  depthBb: number
}

export interface HandsByActionsRequest {
  strategy?: string
  playerCount: number
  depthBb: number
  concreteLineId: number
  actions?: Array<string>
  frequency?: number
}

export interface HandsByActionsResponse {
  holeCards: Array<string>
}

export interface PrewarmResponse {
  openHandleCount: number
}

export interface QueryHandStrategyRequest {
  strategy?: string
  playerCount: number
  depthBb: number
  concreteLineId: number
  holeCards: string
}

export interface QueryHandStrategyResponse {
  inputHoleCards: string
  handCode: string
  actions: Array<ActionResult>
}

export interface PokerHandsRangeOptions {
  dataDir: string
  maxOpenHandles?: number
  verifyChecksums?: boolean
}

export type RangeStoreOptions = PokerHandsRangeOptions

export declare const RangeStore: typeof PokerHandsRange

export interface StatsResponse {
  schemaCount: number
  openHandleCount: number
  knownDimensions: Array<string>
}
