/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ApiResponse<T> {
  code: number
  data: T | null
  message: string | null
}

export interface ActionResult {
  actionName: string
  actionSize: number
  amountBb: number
  frequency: number
  handEv?: number
}

export interface ConcreteLineIdRequest {
  strategy?: string
  playerCount: number
  depthBb: number
  concreteLine: string
}

export interface ConcreteLineIdData {
  concreteLineId: number
}

export interface ConcreteLinesRequest {
  strategy?: string
  playerCount: number
  depthBb: number
  abstractLine?: string
  concreteLine?: string
}

export interface ConcreteLineInfo {
  concreteLineId: number
  abstractLine: string
  concreteLine: string
}

export interface ConcreteLinesData {
  lines: Array<ConcreteLineInfo>
}

export interface AbstractLinesRequest {
  strategy?: string
  drillName?: string
  playerCount: number
  drillDepth: number
}

export interface AbstractLinesData {
  abstractLines: Array<string>
}

export interface DimensionInput {
  strategy?: string
  playerCount: number
  depthBb: number
}

export interface HandsByActionsRequest {
  strategy?: string
  playerCount: number
  depthBb: number
  concreteLineId: number
  actions?: Array<string>
  frequency?: number
}

export interface HandsByActionsResponse {
  holeCards: Array<string>
}

export interface PrewarmResponse {
  openHandleCount: number
}

export interface QueryHandStrategyRequest {
  strategy?: string
  playerCount: number
  depthBb: number
  concreteLineId: number
  holeCards: string
}

export interface QueryHandStrategyResponse {
  inputHoleCards: string
  handCode: string
  actions: Array<ActionResult>
}

export interface BatchQueryItem {
  concreteLineId: number
  holeCards: string
}

export interface QueryBatchRequest {
  strategy?: string
  playerCount: number
  depthBb: number
  items: Array<BatchQueryItem>
}

export interface QueryBatchItemResponse {
  concreteLineId: number
  holeCards: string
  actions?: Array<ActionResult>
  error?: {
    code: number
    message: string
  }
}

export interface QueryBatchData {
  results: Array<QueryBatchItemResponse>
}

export interface PokerHandsRangeOptions {
  dataDir: string
  maxOpenHandles?: number
  verifyChecksums?: boolean
}

export declare class PokerHandsRange {
  constructor(options: PokerHandsRangeOptions)
  getConcreteLineId(request: ConcreteLineIdRequest): ApiResponse<ConcreteLineIdData>
  getConcreteLines(request: ConcreteLinesRequest): ApiResponse<ConcreteLinesData>
  getAbstractLines(request: AbstractLinesRequest): ApiResponse<AbstractLinesData>
  handsByActions(request: HandsByActionsRequest): ApiResponse<HandsByActionsResponse>
  queryHandStrategy(
    request: QueryHandStrategyRequest,
  ): ApiResponse<QueryHandStrategyResponse>
  queryBatch(request: QueryBatchRequest): ApiResponse<QueryBatchData>
  prewarm(request: DimensionInput): ApiResponse<PrewarmResponse>
  stats(): ApiResponse<StatsResponse>
}

export type RangeStoreOptions = PokerHandsRangeOptions

export declare const RangeStore: typeof PokerHandsRange

export interface StatsResponse {
  schemaCount: number
  openHandleCount: number
  knownDimensions: Array<string>
}
